

STATIC_LIB  = $(LIB)/truss.$(SIM).a
SRCS = \
           $(SRC)/truss_watchdog.cpp \
           $(SRC)/truss_verification_top.cpp 


OPT = -DTEST=$(TEST) -DTEST_H=\"$(TEST).h\" -DTEST_NAME=\"$(TEST)\"

build: clean

include $(TRUSS_HOME)/inc/Makefile


