

STATIC_LIB  = $(LIB)/uart.$(SIM).a
SRCS = \
	$(SRC)/uart_configuration.cpp \
	$(SRC)/uart_bfm.cpp \
	$(SRC)/uart_bfm_agent.cpp \
	$(SRC)/uart_checker.cpp \
	$(SRC)/uart_checker_agent.cpp \
	$(SRC)/uart_generator.cpp  \
	$(SRC)/uart_generator_agent.cpp  \



include $(TRUSS_HOME)/inc/Makefile
