

STATIC_LIB  = $(LIB)/tutorial.$(SIM).a
SRCS = \
	$(SRC)/driver.cpp \
	$(SRC)/monitor.cpp \
	$(SRC)/driver_agent.cpp \
	$(SRC)/monitor_agent.cpp \
	$(SRC)/checker.cpp  \
	$(SRC)/generator.cpp  \
	$(SRC)/alu_model.c 

include $(TRUSS_HOME)/inc/Makefile
