

STATIC_LIB  = $(LIB)/top.$(SIM).a
SRCS = \
	$(SRC)/testbench.cpp \
	$(SRC)/../top/uart_interface.cpp \



INCL = -I../../vip/uart -I../../vip/uart_16550 -I../../vip/wishbone -I../top


include $(TRUSS_HOME)/inc/Makefile
