

#redo this, it should only build one test (not an archive), whose name should be passed in from the run script
STATIC_LIB  = $(LIB)/tests.$(SIM).a
SRCS = \
	$(SRC)/tutorial.cpp 

INCL = -I../vip/tutorial -I../testbench/top -I../test_components 

include $(TRUSS_HOME)/inc/Makefile
